title: Keany Vy's Blog
description: "Le blog de Keany Vy KHUN - Juste mon blog..."
author:
  name: "Keany Vy KHUN"
  email: "keanyvy@keemail.me"
  url: "https://thisiskeanyvy.github.io"

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
google_analytics: UA-198877742-1
owner : "Keany Vy's Blog"
year : "2020"
