# Setup
title: Keany Vy Khun's Blog
url: "https://thisiskeanyvy.github.io"
paginate: 1
baseurl: ""

plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Keany Vy KHUN
  url: https://instagram.com/thisiskeanyvy
  email: kinvestisseur@gmail.com

version: 1.0.0

nav:
  - title: Blog
    url: /archive/

  - title: À Propos
    url: /about/
